# Generated by Django 5.2 on 2025-04-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleoncore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('store', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('missing', 'Missing'), ('on_delivery', 'On Delivery'), ('obtained', 'Obtained')], default='missing', max_length=20, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('set_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.PositiveIntegerField(default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom', models.JSONField(blank=True, default=dict, null=True)),
                ('coleoncore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='coleoncore.coleoncore')),
            ],
        ),
    ]
