# Generated by Django 5.2 on 2025-04-09 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleoncore', '0002_coleoncore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='article',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='article',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='number',
        ),
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
        migrations.RemoveField(
            model_name='article',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='set_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='state',
        ),
        migrations.RemoveField(
            model_name='article',
            name='store',
        ),
        migrations.RemoveField(
            model_name='coleoncore',
            name='date',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='coleoncore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coleoncore',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Arrival_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField(blank=True, null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_dates', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=dict)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EURO', 'Euro'), ('YEN', 'Yen'), ('GBP', 'Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='USD', max_length=5, null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_price', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.URLField(blank=True, null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EURO', 'Euro'), ('YEN', 'Yen'), ('GBP', 'Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='USD', max_length=5, null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField(blank=True, null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_dates', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sagas', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('missing', 'Missing'), ('on_delivery', 'On Delivery'), ('obtained', 'Obtained')], default='missing', max_length=20)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='coleoncore.article')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='coleoncore.article')),
            ],
        ),
    ]
