# Generated by Django 5.2 on 2025-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleoncore', '0003_remove_article_amount_remove_article_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coleoncore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coleoncore',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
