# Generated by Django 5.2 on 2025-04-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleoncore', '0004_alter_article_created_at_alter_article_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleoncore',
            name='columns',
            field=models.CharField(default='image:name:status:price'),
        ),
        migrations.AddField(
            model_name='coleoncore',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
