# Generated by Django 5.2 on 2025-04-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleoncore', '0005_coleoncore_columns_coleoncore_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='arrival_date',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_date', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='author',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='delivery_price',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_price', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='description',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='image',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='language',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='name',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='price',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='purchase_date',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_date', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='saga',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saga', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='set',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='status',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='coleoncore.article'),
        ),
        migrations.AlterField(
            model_name='store',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='coleoncore.article'),
        ),
    ]
